In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [3]:
type(a)

numpy.ndarray

In [5]:
#2D array
a2 = np.array([[1,2,3],[4,5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [6]:
#3D array
a3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
print(a2.shape)
print(a3.ndim)
print(a2.dtype)

(2, 3)
2
int64


In [10]:
np.arange(11)
np.arange(2,21)
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [12]:
x = np.array([[7,4,5],
              [1,4,9],
              [2,3,7]])
y = np.array([[2,5,6],
              [5,8,3],
              [8,5,7]]) 
print(x)
print(y)             
              
              
            

[[7 4 5]
 [1 4 9]
 [2 3 7]]
[[2 5 6]
 [5 8 3]
 [8 5 7]]


In [13]:
print(x*y)

[[14 20 30]
 [ 5 32 27]
 [16 15 49]]


In [14]:
print(x@y)  #matrix multiplication

[[74 92 89]
 [94 82 81]
 [75 69 70]]


In [15]:
np.dot(x,y)  #matrix multiplication alternative

array([[74, 92, 89],
       [94, 82, 81],
       [75, 69, 70]])

In [16]:
x.prod() #element wise multiplication of all element in the array

np.int64(211680)

In [17]:
x.mean(axis=0)  #mean of each column

array([3.33333333, 3.66666667, 7.        ])

In [19]:
x.mean(axis=1)  #mean of each row

array([5.33333333, 4.66666667, 4.        ])

In [20]:
print(x.sum())  #sum of all element in the array
print(x.sum(axis=0))  #sum of each column
print(x.sum(axis=1))  #sum of each row

42
[10 11 21]
[16 14 12]


In [21]:
print(x.std())  #standard deviation
print(x.var())  #variance

2.449489742783178
6.0


In [22]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(a,50))
print(np.percentile(a,25))
print(np.percentile(a,75))

5.0
3.0
7.0


In [23]:
c = np.random.randint(11,100, size=(3,4,5))
print(c)

[[[93 26 98 30 93]
  [86 33 48 55 93]
  [53 97 63 57 44]
  [15 48 44 34 80]]

 [[56 51 24 60 73]
  [82 38 63 97 99]
  [84 93 83 83 75]
  [25 22 89 68 28]]

 [[63 48 17 89 43]
  [98 35 54 25 49]
  [95 32 65 74 68]
  [51 91 88 35 70]]]


In [24]:
b = np.random.randint(11,100,size=(4,4))
print(b)

[[72 60 56 41]
 [97 30 24 49]
 [97 39 83 66]
 [24 64 39 24]]


In [25]:
print('2X8')
print(b.reshape(2,8))
print('8X2')
print(b.reshape(8,2))

2X8
[[72 60 56 41 97 30 24 49]
 [97 39 83 66 24 64 39 24]]
8X2
[[72 60]
 [56 41]
 [97 30]
 [24 49]
 [97 39]
 [83 66]
 [24 64]
 [39 24]]


In [26]:
b = np.random.randint(11,100, size=(4,4))
print(b)

[[50 51 29 76]
 [77 23 40 69]
 [35 16 93 75]
 [70 37 76 53]]


In [27]:
print(b[0])  #first row
print(b[0,1]) #first row 2nd column
print(b[-1])  #last row
print(b[:3])  #1st 3 rows
print(b[3:])  #last row
print(b[:,1]) #2nd column


[50 51 29 76]
51
[70 37 76 53]
[[50 51 29 76]
 [77 23 40 69]
 [35 16 93 75]]
[[70 37 76 53]]
[51 23 16 37]
